"""PVGIS v5.2 source — solar PV capacity-factor profiles.

No API key required. Rate limit: 1 request/second recommended.
API: https://re.jrc.ec.europa.eu/api/v5_2/seriescalc
"""
from __future__ import annotations
import json
import logging
import time
import urllib.request
import urllib.error
from typing import Optional

from ..base import BaseTimeseriesSource, ProfileDraft

logger = logging.getLogger(__name__)

# Representative national centroids (lat, lon)
LOCATIONS: dict[str, tuple[float, float]] = {
    "AT": (47.5, 14.5),
    "BE": (50.5, 4.5),
    "BG": (42.7, 25.5),
    "HR": (45.1, 16.4),
    "CY": (35.0, 33.0),
    "CZ": (49.8, 15.5),
    "DK": (55.7, 10.5),
    "EE": (58.6, 25.0),
    "FI": (64.0, 26.0),
    "FR": (46.0, 2.0),
    "DE": (51.2, 10.4),
    "GR": (39.0, 22.0),
    "HU": (47.2, 19.5),
    "IE": (53.0, -8.0),
    "IT": (42.5, 12.5),
    "LV": (56.9, 24.6),
    "LT": (55.2, 24.0),
    "LU": (49.8, 6.1),
    "MT": (35.9, 14.5),
    "NL": (52.3, 5.3),
    "NO": (60.5, 8.5),
    "PL": (52.0, 20.0),
    "PT": (39.5, -8.0),
    "RO": (45.9, 25.0),
    "SK": (48.7, 19.7),
    "SI": (46.1, 15.0),
    "ES": (40.4, -3.7),
    "SE": (60.0, 15.0),
    "CH": (46.8, 8.2),
    "UK": (51.5, -1.0),
}

COUNTRY_NAMES: dict[str, str] = {
    "AT": "Austria", "BE": "Belgium", "BG": "Bulgaria", "HR": "Croatia",
    "CY": "Cyprus", "CZ": "Czech Republic", "DK": "Denmark", "EE": "Estonia",
    "FI": "Finland", "FR": "France", "DE": "Germany", "GR": "Greece",
    "HU": "Hungary", "IE": "Ireland", "IT": "Italy", "LV": "Latvia",
    "LT": "Lithuania", "LU": "Luxembourg", "MT": "Malta", "NL": "Netherlands",
    "NO": "Norway", "PL": "Poland", "PT": "Portugal", "RO": "Romania",
    "SK": "Slovakia", "SI": "Slovenia", "ES": "Spain", "SE": "Sweden",
    "CH": "Switzerland", "UK": "United Kingdom",
}

_BASE = "https://re.jrc.ec.europa.eu/api/v5_2/seriescalc"
_RATE_LIMIT = 2.0  # seconds between requests
_YEAR_MIN = 2005
_YEAR_MAX = 2020   # PVGIS SARAH-2 dataset ends at 2020


def _parse_pvgis_ts(raw: str) -> str:
    """Convert PVGIS "YYYYMMDD:HHMM" to "YYYY-MM-DD HH:00:00"."""
    try:
        date_part, time_part = raw.split(":")
        y = date_part[:4]
        m = date_part[4:6]
        d = date_part[6:8]
        hh = time_part[:2]
        return f"{y}-{m}-{d} {hh}:00:00"
    except Exception:
        return raw


class PVGISSource(BaseTimeseriesSource):
    source_name = "pvgis"

    def fetch(self, location: str, year: int, **kwargs) -> Optional[ProfileDraft]:
        if location not in LOCATIONS:
            logger.warning("PVGIS: no centroid for %s", location)
            return None
        if not (_YEAR_MIN <= year <= _YEAR_MAX):
            logger.debug("PVGIS: year %s out of range [%s, %s], skipping", year, _YEAR_MIN, _YEAR_MAX)
            return None

        lat, lon = LOCATIONS[location]
        url = (
            f"{_BASE}?lat={lat}&lon={lon}"
            f"&startyear={year}&endyear={year}"
            f"&pvcalculation=1&peakpower=1.0&loss=14"
            f"&angle=35&aspect=0&outputformat=json&usehorizon=1"
        )

        try:
            req = urllib.request.Request(
                url,
                headers={"User-Agent": "OpenTech-DB/1.0 (opentech-db@th-deg.de)"},
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.load(resp)
            time.sleep(_RATE_LIMIT)
        except urllib.error.HTTPError as e:
            logger.error("PVGIS HTTP %s for %s %s: %s", e.code, location, year, e.reason)
            time.sleep(_RATE_LIMIT)
            return None
        except Exception as e:
            logger.error("PVGIS fetch failed %s %s: %s", location, year, e)
            return None

        hourly = data.get("outputs", {}).get("hourly", [])
        if not hourly:
            logger.warning("PVGIS: no hourly data for %s %s", location, year)
            return None

        # P is watts for a 1 kWp system → divide by 1000 to get capacity factor
        points = [
            {"timestamp": _parse_pvgis_ts(row["time"]), "value": round(float(row.get("P", 0)) / 1000.0, 6)}
            for row in hourly
            if "time" in row
        ]

        country = COUNTRY_NAMES.get(location, location)
        return ProfileDraft(
            name=f"{location} Utility Solar PV Capacity Factor {year}",
            type="capacity_factor",
            resolution="hourly",
            location=location,
            source=f"PVGIS v5.2 (EU JRC) | lat={lat}, lon={lon} | 1 kWp, 35° tilt, south-facing, 14% losses",
            carrier="solar_irradiance",
            year=year,
            unit="p.u.",
            description=(
                f"Hourly capacity-factor profile for utility-scale fixed-tilt solar PV in {country} ({year}). "
                f"Generated by PVGIS v5.2 (EU JRC) using national centroid (lat={lat}, lon={lon}), "
                f"1 kWp peak power, 35° tilt angle, south-facing, 14% system losses. "
                f"Based on CM SAF SARAH-3 / ERA5 reanalysis solar radiation data."
            ),
            points=points,
            source_name=self.source_name,
        )
